### ISSUE TITLE
Archive Appliance: Determine suitable method to provide a container with the host's IP address.

### ISSUE THREAD

**Issue by iangillingham-stfc** [ISISComputingGroup/isis-aa-config#2]
### Description
It has been demonstrated that we can run the Archiver Appliance in a container (#8438), but for that purpose, the host I address was hard-coded into the container. It's required to be able to provide or preferably determine the host IP address on which the dedicated container gateway resides. As a minimum it could be provided with a run-time switch to `nerdctl`, but would be better if there was a way to do this programmatically (if possible). Similarly the container gateway server port address also should be provided to the container, rather than being hard-coded. The port address should correspond with that defined in `start_gwcontainer.bat`.

### Acceptance criteria
An generic Archiver Appliance image can be run on a host machine and the IP address of the host is known inside the container, such that EPICS_CA_ADDR_LIST can be set to it, along with the relevant port number.

**Comment by Tom-Willemsen** [comment]
In a future branch we do https://github.com/ISISComputingGroup/isis-aa-config/blob/aapoc/aa-init.sh#L13

and get the hostname from an env var, along with some other credentials etc we need.
